services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=UPgrade2023**
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./postgresql/database/data:/var/lib/postgresql/data
