services:
  talentpostgres:
    image: postgres:15.2
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_INITDB_ARGS=${DBINIT}
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./scripts/position-schema.sql:/docker-entrypoint-initdb.d/position-schema.sql
    networks:
      talentnetwork:
        ipv4_address: 172.18.0.2
  
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL: jdbc:postgresql://172.18.0.2:5432/${DBUSER}
      - SONAR_JDBC_USERNAME: ${DBUSER}
      - SONAR_JDBC_PASSWORD: ${DBPASSWORD}
    ports:
      - '9000:9000'
    expose:
      - 9000
    networks:
      talentnetwork:
        ipv4_address: 172.18.0.3

networks:
  talentnetwork:
    name: "talentnetwork"
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/28"
