services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=UPgrade2023**
      - POSTGRES_USER=sonar
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./postgresql/database/data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:9.9.0-community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=UPgrade2023**
    volumes:
      - ./sonarqube_conff:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
networks:
  sonarnet:

