services:
  talentpostgres:
    image: postgres:15.2
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_INITDB_ARGS=${DBINIT}
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/position-schema.sql
    networks:
      talentnetwork:
        ipv4_address: 172.18.0.2

networks:
  talentnetwork:
    name: "talentnetwork"
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/28"
