name: Build Position Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "dev"
      - "main"

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/positionservice:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/positionservice:latest
  DUSER: ${{ secrets.DOCKERHUB_USERNAME }}
  DTOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERFILE: ./src/Presentation/PositionServiceApi/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DUSER }}
          password: ${{ env.DTOKEN }}
      - name: Docker build test tag
        uses: docker/build-push-action@v4
        with:
          build-args: |
            gituser=${{ secrets.USERNAME }}
            gitpass=${{ secrets.PAT }}
            dbpass=password
            dbuser=user
            dbport=1111
            dbname=db
            dbhost=localhost
            mquser=user
            mqpass=mqpassword
            mqhost=localhost
            mqport=2222
          context: .
          load: true
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.TEST_TAG }}
      - name: Test the container
        shell: bash
        run: |
          CID=$(docker run -d --rm -p '8080:80' ${{ env.TEST_TAG }})
          if [[ -n "$CID" ]]; then
            sleep 5
            docker exec "$CID" /bin/bash -c "/bin/echo 'this is within the container'" && \
            docker stop "$CID"
            exit 0
          else
            echo "Unable to run container with test image" 1>&2 >> "$GITHUB_OUTPUT"
            exit 1
          fi
      - name: Push the container
        uses: docker/build-push-action@v4
        with:
          build-args: |
            gituser=${{ secrets.USERNAME }}
            gitpass=${{ secrets.PAT }}
          context: .
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.LATEST_TAG }}
          push: true

